### ISSUE TITLE
Impossible to download SVG file 

### ISSUE THREAD

**Issue by Tantoale** [densitydesign/raw#135]
Hi, 
the download is not working. I made my chart several times and everything is fine but when I click on the download SVG file, the program just open the chart in the a new browser window and not downloading it as a vector. 

Can you fix it?

Thanks

Alessia
![schermata 2017-05-15 alle 21 23 21](https://cloud.githubusercontent.com/assets/28715133/26075219/d0ed5ee8-39b4-11e7-9765-d118b4f4554f.png)
![schermata 2017-05-15 alle 21 23 42](https://cloud.githubusercontent.com/assets/28715133/26075220/d114ceec-39b4-11e7-9031-f78c64952e47.png)

**Comment by mikima** [comment]
Hello, Safari handles in a different way the download: instead of saving it locally, it opens a new tab with the visualisation in it.
Meanwhile, you can solve the issue or using another browser, or saving the Safari page.
Click on "File" > "save as..". In the window, select "page source" as "format". Type the name of your visualization followed by ".svg"
<img width="557" alt="screen shot 2017-05-18 at 09 38 22" src="https://cloud.githubusercontent.com/assets/907536/26191421/191ab4f4-3bae-11e7-9d16-9ba258e278ad.png">
