### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KrishnaPG** [densitydesign/raw#82]
Sorry for reopening this issue. But could you please reconsider the right license option for this?

As such this work is good and your option for LGPL allows commercial usage. However, given the LGPL v3 nature that user be given a choice to replace the module with any other module of their own choice with equal functionality, this puts a big restriction on the application designers. Especially when using in web-related scenario it is not that easy for any web-application to let their users replace the module with any version of their choice.

In this respect, could you please consider some other commercial friedly license apart from LGPL? Something like BSD, Apache or MIT? They let you get you the right credit for your work without putting additional restrictions on the application designers.

**Comment by buremba** [comment]
Is there any update on this issue?

**Comment by haneefmubarak** [comment]
Here, let's try pinging all the relevant people again: @densitydesign @giorgiocaviglia @btford @mikima @giorgiouboldi @constanzaur @Hoverbear @uf0 @fcurella @ryanponce

**Comment by fcurella** [comment]
RAW is licensed under LGPL since March 12 2014: https://github.com/densitydesign/raw/blob/master/LICENSE

I think this issue can be closed.

**Comment by haneefmubarak** [comment]
Well, @fcurella, the problem here IS that the RAW is licensed under the LGPL. On the web, it is not easily possible to allow _relinking_ without revealing the code calling it. Therefore, on the, web, a license such as the MIT or BSD license is more appropriate.

**Comment by boogheta** [comment]
And why wouldn't one want to reveal the code calling it ? It's always nice to benefit from other works, so just share also yours for others! :)
This is the real free software spirit, building an ecosystem of resources for everyone:!

**Comment by haneefmubarak** [comment]
@boogheta Well, let's say you build a website. As linking and calling in the conventional manner are not well defined on the web, one could well say that any form of embedding or using any JS or CSS resource could be interpreted as calling.

Given that premise, if you were to build a website that at all used `densitydesign/raw`, you would have to release the source for every single page that even interacted with `raw`. This already gets pretty bad. Now, let's say that all of your pages are served by a  backend application that you have written, similar to the vast majority of the websites on the internet (Google, GitHub, StackExchange, etc.). Well, in that case, you'd have to open source the entirety of your website.

Many owners of larger commercial websites, including the ones I listed, are highly unlikely to do that. Instead, they will just make their own internal (likely full closed source) tools similar to `raw`. Given their expertise, experience, and the benefit of seeing how a tool like `raw` works, they will probably be able to construct much better tools with more features and whatnot. However, no one else will receive the benefit of those tools. 

As a result, there shall exist a net loss to the community, as larger commercial websites will have more advanced tools while the community who is willing to fully open source their websites under a specific license (GPL or LGPL - even open source websites using MIT or BSD couldn't use `raw`) would be stuck with something that would have less development power behind it. Meanwhile...

---

If `raw` were to be relicensed under BSD or MIT, any website would be able to use it. Therefore, anyone needing similar functionality would likely use the tool or extend it. This includes larger commercial sites who have large development abilities due to their staffing. Should they find that something is lacking, they can simply extend it and then everyone can use it.

However, one could validly point out that said companies could always keep their improvements to themselves and not contribute back. That is definitely a possibility. However, sooner or later if they wish to keep receiving the improvements, they will find that continuously merging changes from upstream (ie: this repository) will become somewhat of a hassle. This will provide a strong incentive for them to send changes back to this repository for merging.

As a result, `raw` would be more widely usable and would also likely receive more contributions. Everyone would be able to use the same tool and there would be a more level playing field.

**Comment by haneefmubarak** [comment]
@KrishnaPG did you get any response?

**Comment by RouxRC** [comment]
Raw is just a web interface that reuses pieces of d3.js adapted from bl.ocks.org, anyone can reuse those with no regard whatsoever to raw and I don't see what you would want to import from raw itself in another website except for an output generated svg which you can totally do without any problem, lgpl does not cover the products resulting from the tool...
Anyways, when I read someone saying "This already gets pretty bad" regarding opening the source of a website, well, no need to argue more...

**Comment by haneefmubarak** [comment]
@RouxRC `raw` provides a library interface for use. AFAICT the web interface is just a demo of its capabilities.

---

> Anyways, when I read someone saying "This already gets pretty bad" regarding opening the source of a website, well, no need to argue more...

Here's the thing. People don't mind open source. Actually, people really love open source products. See, open source products allow various people and companies to share the effort of building the stuff they all collectively need so they can focus their efforts on building their specialized product.

For some people and vendors, their product or service can be open sourced and there do exist models where they can monetize their product/service. For other people and vendors, their product/service may not be monetizable in an open source fashion. Many _components_ of their product may be open sourceable, but not their core product.

For instance, take Netflix or Spotify. They use and contribute back to many open source projects, yet they obviously can't open source their products. Another excellent example would be Google with Android and the Play Store. Android as a project (AOSP - Android _Open Source_ Project) is open sourced, but the infrastructure that allows content developers to easily distribute their media to consumers is closed source.

In this way, we can see that while often large swaths of code may be open sourceable, there do exist portions of code that may not be as easily open sourced.

**Comment by RouxRC** [comment]
This is a philosophy: the typical "opensource" business one.
I prefer the free software community one...
What costs Netflix or Spotify and keeps them in place is the physical infrastructure, not the code. The only pieces of code worth keeping closed for content distributions would be drm-like ones, and regarding those, well, no need to argue much more either...

**Comment by RouxRC** [comment]
PS: if you consider the web interface a simple demo to what can actually be done, this means you have ideas of useful viz to add to the existing `raw` stack, then why not share it back with @densitydesign?
When you look closely at this discussion, you are basically just arguing plenty just to avoid answering this real question.

**Comment by haneefmubarak** [comment]
@RouxRC my point is that even if someone doesn't have anything to contribute back to the `raw` project, the viral nature of the LGPL means that someone would have to open source their entire front end.

> if you consider the web interface a simple demo to what can actually be done, this means you have ideas of useful viz to add to the existing `raw` stack, then why not share it back with @densitydesign and let everybody enjoy it?

What I mean is that the web "interface" is quite _literally_ a demo. `raw` is not a full application. `raw` is a _library_ (like `jQuery`, `Angular`, etc.). It's sort of like the difference between WebKit / CWF (libraries) and Safari / Chrome (applications). As such, the _normal usecase_ is to call `raw` from within a web application or script.

In other words, you can't even use `raw` the way it ought to be used (as a library), without being infected by the LGPL and being forced to open source your ***ENTIRE FRONT END***.

I think our misunderstanding here is that you believe that the core functionality of `raw` is as a standalone application. However, in reality, the main functionality of `raw` is as a library; since libraries on the web are not relinkable in the conventional sense, `raw`'s LGPL effectively acts as a GPL - which isn't practical to use on the web (for HTML/CSS/JS frameworks, scripts, and libraries), which is precisely why stuff on the web is usually licensed under an MIT license (see [jQuery](https://jquery.org/license/), [Meteor](https://github.com/meteor/meteor/blob/devel/LICENSE.txt), [AngualrJS](https://github.com/angular/angular.js/blob/master/LICENSE), and even [d3](https://github.com/mbostock/d3/blob/master/LICENSE) ([the library that `raw` is based off of](https://github.com/densitydesign/raw/blob/master/README.md))).

**Comment by RouxRC** [comment]
Plenty of the web is "infected" as you say with GPL and quite happy with it, again, there are two philosophies, your mecantile one, and the other, please stop trying to impose yours to people who obviously do not share it.

**Comment by haneefmubarak** [comment]
@RouxRC I'm not quite imposing a philosophy on anyone, considering that I'm not suggesting a viral license. Additionally, you seem to have missed out on the fact that in this thread, 4 people (including myself) appear to be taking adopting "my philosophy", 1 hasn't stated a position, and only 2 including yourself are taking a hardliner stance. Out of all of the people who have stated a position, only two have actually contributed to the codebase of the project, and these 2 both appear to have "agreed with my philosophy".

Also, please stop using childish ad hominem attacks such as "your mercantile one" and such. It does little to further debate or progress. Instead, make actual, valid arguments based on reasoning and data, not feelings/philosophies/etc.

---

The sort of things that are GPL'ed on the web as you mentioned are things like Wordpress (backend) and such. I've outlined reasons as to why stuff on the web (ie: frontends and especially ***javascript libraries***) are not conventionally (L)GPL'ed, but [here's a list of answers on StackOverflow as to why JS libraries should not be (L)GPL'ed](http://stackoverflow.com/a/1239727/2334407).

---

As for a precise use case: Let's say you want to make a simple webapp. Let's say that this is a simple accounting webapp. It should be able to take in data from a variety of formats and process it. Later, it should be able to make graphs and charts based on the data resulting from its processing. As it gathers more and more data from whatever sources you feed into it (exports from a variety of applications), it can make better predictions for you so you can better plan your finances. Obviously, since you want to make this a simple but extremely secure app, you don't even want any data leaving the users' computers, so all processing must be done in browser.

Now, you could put together a variety of JS libraries and make them work together in order to do this. Or, given that `raw` is actually a library, you could use these portions and then just write your actual processing code:

 - `raw.parser()` and related methods would allow you to build quick, simple parsers against the various data inserted into the webapp
 - The `model`, `dimension`, and `chart` objects would allow you to easily make charts and graphs.

There you have it. A simple use case. Now, given that `raw` is licensed under LGPL and there isn't really such a thing as linking on the web (except using loopholes - see the second post from the top), the license really acts as GPL. Due to its viral nature, the author of such a webapp may not be able to use `raw`, because the viral clauses would force him or her to open up the entirety of their app frontend under the same license and they may not wish to do so.

Therefore, they might likely just use a variety of other libraries, and if they had any unifying changes, well, they would likely just keep it to themselves. 

However, if they were able to use a MIT or BSD licensed `raw`, they would feel free to use it in their app under any circumstances. If they came up with improvements to the overall functionality of the library, they could contribute it back.

---

Finally, none of the well known frontend of the web is infected with the GPL. ZERO of the top 10 JS libraries and top 10 JS frameworks use the GPL. ZERO.

The vast majority of them use the MIT license, a couple use the BSD license, and I think one or two use the Apache License.

**Comment by RouxRC** [comment]
Repeating in loops the same things over huges paragraphs does not make them better arguments, jujst trolling.
Especially when you keep adding nonsense each time.
Nope, wordpress is NOT a backend, it's both and a lot of its plugins propose mainly javascript pieces of code.
Same thing for raw, and your examples do not show in any way why you would need to reuse it:
- the csv parser is explicitely inspired from an unlicenced tutorial piece of code from the web (and don't tell me you're having issues finding a javascript csv parser under bsd/mit...)
- the model/dimension/chart are just basic wrapers around d3's api and are especially built for raw's frontend, so which would need it to be completely rewritten for other use cases than just adding viz to the front...
The fact that a majority of JS libraries chose Google's view is certainly true, but it absolutely does not make it the default choice for everyone, just sheeps...
I'm only saying this is the BSD Vs GPL argument all over, and you don't bring any new argument, this debate is unifinishable, it's just a pjilosophical choice one, and your way of insisting by including false arguments so far from the actual usecase here is really annoying...

**Comment by haneefmubarak** [comment]
Wordpress runs *server-side*. When running WP, you do ***NOT*** distribute code to others. When running in browser JS, you do effectively do distribute code to others.

It is doable to use multiple libraries, however, using a unified library generally makes things easier.

The vast majority of JS libraries did not "choose Google's view" (do note that I am not affiliated with Google or Facebook or Microsoft or Apple or Twitter or Amazon etc. at the current time), they chose the rational approach to take with anything being distributed over the internet. It is not people fanboying over licenses or bowing to their corporate masters or any such ridiculous notion - it is ***rational people capable of logical thinking*** considering what licensing schemes are **feasible and useful** for client-side web libraries.

---

Now @RouxRC, it honestly saddens me that you appear to be uncapable of conveying your arguments without the use of ad hominems or other such fallacies (perhaps you have no legitimate arguments?), so I shall try to walk through this in your manner:

 - This isn't the BSD vs GPL argument, this is the "both were written back in the days of static and dynamic binary linking and the web functions differently so we must look at things differently" line of thought
 - I haven't included anything factually incorrect AFAICT thus far, compared to your farcical assertions which do indeed show both a deep seated allegiance to the GPL and a strong lack of understanding relating to modern web technologies and their licensing
 - When a large number of relatively ingenious people independently sit down and think deeply and then all arrive at the  conclusion that perhaps the GPL isn't suited at all for the web and then proceed to license their JS library code under MIT/BSD/Apache, that isn't "sheep thinking", it's rational logical thinking that incorporates the facts at hand. If some other idiot starts harping on about "philosophies" and such bullshit while presenting no arguments that weren't considered by the prior mentioned ingenious people, it just shows that they have a strong affinity for something and are incapable of thinking rationally about it.
 - If someone tries to explain the reasoning to such a person and their only response is that "you are incorrect" without actually explaining which parts are incorrect and why, clearly they are either blindly following their FSF masters, or they cannot be bothered to think rationally and just with to argue, which would make them a **troll**.
 - Yet still if they think that the vast array of arguments against are simple versions of the same argument repeated and that the other party which is actually trying to explain to them is trolling, this demonstrates a massive lack of fundamental cognitive functionality.

Your actions, words, and reasoning (or rather a lack thereof) thus far demonstrate a lot about you. Perhaps you would do well to actually find a legitimate argument if one exists and present it instead of trolling.

**Comment by RouxRC** [comment]
We could discuss your definitions of frontend/backend vs server/client for hours but this I really feel like this is pointless (surprise: raw is actually... pieces of the 4, as for wordpress...).

I already told you I don't believe there's any need to argue more: this is a philosophical choice, on which we radically disagree. I have a strong preference for the cocreation of common goods over the fully liberal model.

And I have not read one single argument actually explaining why it could not apply to websites. Well actually it does already apply to plenty, including raw here, but also big projects who try to propose community-based alternatives to the big companies in place. And a lot of people will keep building things, including tools fully JS clientside only, and release them in the sharing ecosystem. If some refuse to contribute to copyleft projects because they're too eager to share their own code, well too bad, but people will continue to develop without them perfectly well.

So you can keep describing reality as we both perfectly know it just in the hope the way you fashion it will convince me or others your view is the right one, but again it's not a definitive discussion where there's someone right and someone wrong: just two very different conception of coding and more generally the society.

Won't feed you anymore from now on...

**Comment by mikima** [comment]
The license has been changed to Apache 2.0

**Comment by haneefmubarak** [comment]
Thanks @mikima!
